tags:
  coding:
    group: 開發
    icon: 💻
    keywords:
    - code
    - programming
    - developer
    - software
    - engineering
    - coding
    - 程式
    - 程式設計
    - 開發者
    - coding
    - web dev
    - app dev
    - mobile dev
    - system design
    - cs dojo
    - developedbyed
    - epcdiy
    - fireship
    - coding tech
    - academind
    - philipp lackner
    - very good ventures
    - theo
    - t3.gg
    - convex
    - web dev simplified
    - the coding sloth
    - cloud tech
  flutter:
    group: 開發
    icon: 🐦
    keywords:
    - flutter
    - dart
    - resocoder
    - filledstacks
    - flutter community
    - flutter explained
  AI:
    group: 開發
    icon: 🤖
    keywords:
    - artificial intelligence
    - machine learning
    - deep learning
    - deepmind
    - anthropic
    - claude
    - openai
    - gpt
    - llm
    - large language model
    - generative ai
    - gen ai
    - ai safety
    - ai assistant
    - ai code editor
    - ai nerd
    - firebase
    - google deepmind
    - google for developers
    - visual studio code
  backend:
    group: 開發
    icon: ⚙️
    keywords:
    - backend
    - server
    - api
    - database
    - firebase
    - google cloud
    - cloud
    - 雲端
    - serverless
    - infrastructure
    - devops
    - linux
  frontend:
    group: 開發
    icon: 🎨
    keywords:
    - frontend
    - front-end
    - front end
    - css
    - html
    - javascript
    - react
    - vue
    - angular
    - web dev
    - web development
    - web developer
    - 網頁
  google:
    group: 開發
    icon: 🔵
    keywords:
    - google
    - firebase
    - google cloud
    - google for developers
    - google deepmind
    - gdg
    - line developers
  tech-review:
    group: 開發
    icon: 📱
    keywords:
    - review
    - 評測
    - 開箱
    - tech review
    - terry chen
    - 泰瑞
    - 先看评测
    - 作业本
    - 爱否
    - 极创意
    - mediastorm
    - 影视飓风
    - 曲博
  diy:
    group: 開發
    icon: 🔧
    keywords:
    - diy
    - 水電
    - 宅水電
    - 超認真少年
    - 超認真
    - arduino
    - maker
    - 自造
  chinese:
    group: 語言
    icon: 🀄
    keywords:
    - 中文
    - chinese
    - 普通話
    - mandarin
  english:
    group: 語言
    icon: 🇬🇧
    keywords:
    - english
    - 英文
    - 英語
    - st english
    - esl
  japanese:
    group: 語言
    icon: 🇯🇵
    keywords:
    - japanese
    - 日文
    - 日語
    - 日本語
    - 秋山耀平
    - 秋山燿平
    - 出口日語
    - 日本
    - 東京
  piano:
    group: 音樂
    icon: 🎹
    keywords:
    - piano
    - 鋼琴
    - marasy
    - pianist
    - ピアノ
    - めいぷる
    - maple piano
    - 演奏
  music:
    group: 音樂
    icon: 🎵
    keywords:
    - music
    - song
    - cover
    - guitar
    - composer
    - 音樂
    - 吉他
    - 樂團
    - 歌手
    - 作曲
    - nicechord
    - 好和弦
    - musecow
    - 音樂家
  finance:
    group: 財經
    icon: 📈
    keywords:
    - finance
    - invest
    - stock
    - 股票
    - 投資
    - 理財
    - 財經
    - 經濟
    - caven
    - 成長家
    - 卡爾先生
    - 小新新講
    - 艾爾文
    - 錢進前十趴
    - 這leo人
    - 美股
    - nick 美股
    - 春哥
    - acquired
    - startup
    - 商業
    - 創業
    - allen lab
    - bill gates
  news:
    group: 財經
    icon: 📰
    keywords:
    - news
    - politics
    - 時事
    - 新聞
    - 政治
    - 公視
    - 新聞實驗室
    - dcard報報
    - cheap
    - 黃國昌
    - 曾博恩
    - 博恩
  science:
    group: 知識
    icon: 🔬
    keywords:
    - science
    - scientific
    - physics
    - biology
    - chemistry
    - 科學
    - 科普
    - nature video
    - scishow
    - pansi
    - 泛科學
    - kurzgesagt
    - nutshell
    - crashcourse
    - big think
    - mark rober
    - reallifelore
    - geography now
  education:
    group: 知識
    icon: 📚
    keywords:
    - education
    - learn
    - tutorial
    - 教學
    - 課程
    - 知識
    - history
    - 歷史
    - 回形针
    - paperclip
    - 下一本
    - 讀什麼
    - 阅部客
    - 閱讀
    - 罗振宇
    - 罗辑思维
    - 邏輯思維
    - 老師好
    - 何同学
  documentary:
    group: 知識
    icon: 🎥
    keywords:
    - documentary
    - 紀錄片
    - discovery
    - 國家地理
    - national geographic
    - nature video
  art:
    group: 知識
    icon: 🎨
    keywords:
    - drawing
    - painting
    - illustration
    - procreate
    - proko
    - sketch
    - 素描
    - 水彩
    - 油畫
    - 插畫
    - 有點艺思
    - 刘采翎
    - 創意
  health:
    group: 知識
    icon: 🏥
    keywords:
    - health
    - medical
    - medicine
    - 健康
    - 醫療
    - 醫學
    - 醫生
    - 蒼藍鴿
    - 滄瀾教主
    - 漢醫
    - 中醫
    - 當代漢醫苑
    - 保健
    - 養生
  lifestyle:
    group: 生活
    icon: ☕
    keywords:
    - lifestyle
    - vlog
    - 日常
    - 生活
    - ace moment
    - gq taiwan
    - 穿搭
    - 時尚
    - 居家
    - lo-fi house
    - living big
    - tiny house
    - erik van conover
    - 我是老爸
    - 跳脫
    - 嘟式圈
  travel:
    group: 生活
    icon: ✈️
    keywords:
    - travel
    - 旅遊
    - 旅行
    - lonely planet
    - 景點
    - 背包客
    - 出國
    - the dodo men
    - 嘟嘟人
    - paolo fromtokyo
    - 台客不在家
    - 台客劇場
    - 一条
    - 張修修
    - 真奈特
    - 茶里
  real-estate:
    group: 生活
    icon: 🏠
    keywords:
    - real estate
    - 房地產
    - 買房
    - 賞屋
    - 房屋
    - 不動產
    - 移民
    - 東京購屋
    - 看房
    - 租寓
    - 南投買好房
    - 美國房地產
  fitness:
    group: 生活
    icon: 💪
    keywords:
    - fitness
    - workout
    - gym
    - 健身
    - 運動
    - 訓練
    - 肌肉
    - 增重
    - 卓叔
    - 減脂
    - 拳擊
    - hu boxing
    - 古月拳館
    - 拳擊小潘
    - james tripp
  entertainment:
    group: 娛樂
    icon: 🎬
    keywords:
    - entertainment
    - comedy
    - funny
    - 搞笑
    - 娛樂
    - 綜藝
    - 迷因
    - onion man
    - 洋蔥
    - 反正我很閒
    - 啾啾鞋
    - steven he
    - zack d films
    - 蔡阿嘎
    - jordan has no life
    - j-bao
    - 賤葆
    - dcard video
  gaming:
    group: 娛樂
    icon: 🎮
    keywords:
    - game
    - gaming
    - 遊戲
    - 電玩
    - 實況
    - 最強聯盟
    - teogaming
  podcast:
    group: 娛樂
    icon: 🎙️
    keywords:
    - podcast
    - pod cast
    - 廣播
    - 音頻
    - 音頻節目
    - 博音
    - 滄瀾教主
    - 知識長
    - 國威
    - 錢進前十趴
    - pocast
    - audio
    - 電台
    - 訪談節目
